// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SitesMonitoring.Models;
using System;

namespace SitesMonitoring.Data.Migrations
{
    [DbContext(typeof(SitesMonitoringContext))]
    [Migration("20180113222106_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SitesMonitoring.Models.Settings", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("WaitSecond");

                    b.HasKey("ID");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("SitesMonitoring.Models.Site", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("URL");

                    b.HasKey("ID");

                    b.ToTable("Site");
                });
#pragma warning restore 612, 618
        }
    }
}
